& {
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$Findings = [Collections.Generic.List[object]]::new()
$Summary = [Collections.Generic.List[object]]::new()
$Inventory = [Collections.Generic.List[object]]::new()
$Notes = [Collections.Generic.List[string]]::new()
$CommandCache = @{}
function Get-PSCPCount { param([object]$Value) return @($Value).Count }
function Get-PSCPProp { param([object]$Object,[ValidateNotNullOrEmpty()][string]$Name) if($null -eq $Object){ return $null }; $Property = $Object.PSObject.Properties[$Name]; if($Property){ return $Property.Value }; return $null }
function Get-PSCPLocation { param([ValidateNotNull()][string]$Text,[int]$Index) if($Index -le 0){ return [pscustomobject]@{Line=1;Column=1} }; $Prefix = $Text.Substring(0,[Math]::Min($Index,$Text.Length)); $Lines = @($Prefix -split "`r?`n"); return [pscustomobject]@{Line=(Get-PSCPCount -Value $Lines);Column=($Lines[-1].Length + 1)} }
function Get-PSCPRating { param([int]$Score) switch($Score){ {$_ -ge 90}{return 'High'} {$_ -ge 75}{return 'Good'} {$_ -ge 50}{return 'Moderate'} {$_ -ge 25}{return 'Low'} default{return 'Very low'} } }
function Add-PSCPFinding { param([ValidateNotNullOrEmpty()][string]$File,[ValidateSet('Critical','Error','Warning','Review')][string]$Severity,[ValidateNotNullOrEmpty()][string]$Area,[int]$Line,[int]$Column,[ValidateNotNullOrEmpty()][string]$Message,[string]$Text='') $null = $Findings.Add([pscustomobject]@{File=$File;Severity=$Severity;Area=$Area;Line=$Line;Column=$Column;Message=$Message;Text=(($Text -replace '\s+',' ').Trim())}) }
function Test-PSCPEap { param([System.Management.Automation.Language.Ast]$Ast) return ((Get-PSCPCount -Value @($Ast.FindAll({param($Node) $Node -is [System.Management.Automation.Language.AssignmentStatementAst] -and $Node.Left -is [System.Management.Automation.Language.VariableExpressionAst] -and $Node.Left.VariablePath.UserPath -match '^(global:|script:|local:)?ErrorActionPreference$' -and $Node.Right.Extent.Text -match '(?i)[''\"]Stop[''\"]|::Stop\b|ActionPreference\]::Stop|[''\"]Inquire[''\"]|::Inquire\b'},$true))) -gt 0) }
function Get-PSCPCodeText { param([ValidateNotNull()][string]$Raw,[object[]]$Tokens) $Output = $Raw; foreach($Token in @($Tokens | Where-Object -FilterScript { $_.Kind -in 'Comment','StringExpandable','StringLiteral','HereStringExpandable','HereStringLiteral' } | Sort-Object -Property { $_.Extent.StartOffset } -Descending)){ $Start = [int]$Token.Extent.StartOffset; $Length = [int]($Token.Extent.EndOffset - $Token.Extent.StartOffset); if($Length -gt 0 -and $Start -ge 0 -and ($Start + $Length) -le $Output.Length){ $Output = $Output.Remove($Start,$Length).Insert($Start,(' ' * $Length)) } }; return $Output }
function Add-PSCPSummary { param([ValidateNotNullOrEmpty()][string]$File,[int]$Start,[string]$Raw,[object[]]$Commands,[object[]]$Functions,[object[]]$Parameters,[object[]]$Variables) $FileFindings = if((Get-PSCPCount -Value $Findings) -gt $Start){ @($Findings[$Start..((Get-PSCPCount -Value $Findings)-1)]) } else { @() }; $Critical = Get-PSCPCount -Value @($FileFindings | Where-Object -FilterScript {$_.Severity -eq 'Critical'}); $Errors = Get-PSCPCount -Value @($FileFindings | Where-Object -FilterScript {$_.Severity -eq 'Error'}); $Warnings = Get-PSCPCount -Value @($FileFindings | Where-Object -FilterScript {$_.Severity -eq 'Warning'}); $Reviews = Get-PSCPCount -Value @($FileFindings | Where-Object -FilterScript {$_.Severity -eq 'Review'}); $Lines = if($Raw){ Get-PSCPCount -Value @($Raw -split "`r?`n") } else { 0 }; $Score = [Math]::Max(0,100-($Critical*30)-($Errors*15)-($Warnings*5)-[Math]::Min(20,$Reviews)); $UniqueCommands = Get-PSCPCount -Value @($Commands | ForEach-Object -Process {$_.C} | Sort-Object -Unique); $null = $Summary.Add([pscustomobject]@{File=$File;Score=$Score;Rating=(Get-PSCPRating -Score $Score);Critical=$Critical;Error=$Errors;Warning=$Warnings;Review=$Reviews;Lines=$Lines;Commands=$UniqueCommands;Functions=(Get-PSCPCount -Value $Functions);Parameters=(Get-PSCPCount -Value $Parameters);Variables=(Get-PSCPCount -Value $Variables);FindingsPer100Lines=if($Lines){[Math]::Round(((Get-PSCPCount -Value $FileFindings)/[Math]::Max(1,$Lines))*100,2)}else{Get-PSCPCount -Value $FileFindings}}) }
$null = $Notes.Add('Autonomous mode v3.4: scans current directory recursively. Target scripts are parsed/scanned only, not executed. PSScriptAnalyzer auto-installs if missing.')
try{ $PssaModule = Get-Module -ListAvailable -Name PSScriptAnalyzer | Select-Object -First 1 } catch { $PssaModule = $null; $null = $Notes.Add("PSScriptAnalyzer discovery failed: $($_.Exception.Message)") }
if(-not $PssaModule){ try{ Install-Module -Name PSScriptAnalyzer -Scope CurrentUser -Force -AllowClobber -ErrorAction Stop; try{ $PssaModule = Get-Module -ListAvailable -Name PSScriptAnalyzer | Select-Object -First 1 } catch { $PssaModule = $null }; if($PssaModule){ $null = $Notes.Add("PSScriptAnalyzer installed/found: $((Get-PSCPProp -Object $PssaModule -Name Version))") } else { $null = $Notes.Add('PSScriptAnalyzer install completed but module was not found; PSSA skipped.') } } catch { $null = $Notes.Add("PSScriptAnalyzer install failed; PSSA skipped: $($_.Exception.Message)") } }
if($PssaModule){$null=$Notes.Add("PSScriptAnalyzer module available: $((Get-PSCPProp -Object $PssaModule -Name Version))")}else{$null=$Notes.Add('PSScriptAnalyzer module unavailable; PSSA diagnostics unavailable.')}
$PssaAvailable = $false
$PssaDiag = 0
if($PssaModule){ try{ Import-Module -Name PSScriptAnalyzer -ErrorAction Stop; $PssaAvailable = [bool](Get-Command -Name Invoke-ScriptAnalyzer -ErrorAction Stop) } catch { $null = $Notes.Add("PSScriptAnalyzer import/check failed; PSSA skipped: $($_.Exception.Message)") } }
try{ $Files = @(Get-ChildItem -Path . -Recurse -File -ErrorAction Continue | Where-Object -FilterScript { $_.Extension -in '.ps1','.psm1','.psd1' } | Sort-Object -Property FullName -Unique) } catch { $Files = @(); $null = $Notes.Add("File enumeration failed: $($_.Exception.Message)") }
if((Get-PSCPCount -Value $Files) -eq 0){ 'No PowerShell files found.'; return }
foreach($File in $Files){
$RelativePath = $File.FullName; $StartFinding = Get-PSCPCount -Value $Findings; $Raw = ''; $Commands=@(); $Functions=@(); $Parameters=@(); $Variables=@()
try{
try{ $RelativePath = Resolve-Path -LiteralPath $File.FullName -Relative -ErrorAction Stop } catch { $RelativePath = $File.FullName }
$StartFinding = Get-PSCPCount -Value $Findings
try{ $Raw = Get-Content -LiteralPath $File.FullName -Raw -ErrorAction Stop } catch { Add-PSCPFinding -File $RelativePath -Severity Critical -Area Read -Line 0 -Column 0 -Message $_.Exception.Message; Add-PSCPSummary -File $RelativePath -Start $StartFinding -Raw $Raw -Commands $Commands -Functions $Functions -Parameters $Parameters -Variables $Variables; continue }
$Tokens = $null; $ParseErrors = $null; $Ast = [System.Management.Automation.Language.Parser]::ParseFile($File.FullName,[ref]$Tokens,[ref]$ParseErrors); $CodeText = Get-PSCPCodeText -Raw $Raw -Tokens @($Tokens)
foreach($ParseError in @($ParseErrors)){ if($null -ne $ParseError){ Add-PSCPFinding -File $RelativePath -Severity Critical -Area Parser -Line $ParseError.Extent.StartLineNumber -Column $ParseError.Extent.StartColumnNumber -Message $ParseError.Message -Text ([string]$ParseError.Extent.Text) } }
$CommandAsts = @($Ast.FindAll({param($Node) $Node -is [System.Management.Automation.Language.CommandAst]},$true))
$Commands = @($CommandAsts | ForEach-Object -Process { $Name = $_.GetCommandName(); if($Name){ [pscustomobject]@{C=$Name;L=$_.Extent.StartLineNumber;K=$_.Extent.StartColumnNumber;T=$_.Extent.Text} } })
$Functions = @($Ast.FindAll({param($Node) $Node -is [System.Management.Automation.Language.FunctionDefinitionAst]},$true) | ForEach-Object -Process {$_.Name} | Sort-Object -Unique)
$Parameters = @($Ast.FindAll({param($Node) $Node -is [System.Management.Automation.Language.ParameterAst]},$true))
$Variables = @($Ast.FindAll({param($Node) $Node -is [System.Management.Automation.Language.VariableExpressionAst]},$true) | ForEach-Object -Process {$_.VariablePath.UserPath} | Sort-Object -Unique)
$Attributes = @($Ast.FindAll({param($Node) $Node -is [System.Management.Automation.Language.AttributeAst]},$true))
$Requirements = $Ast.ScriptRequirements
$RequiredVersion = Get-PSCPProp -Object $Requirements -Name RequiredPSVersion; if(-not $RequiredVersion){ $RequiredVersion = Get-PSCPProp -Object $Requirements -Name RequiredVersion }
if($RequiredVersion -and $PSVersionTable.PSVersion -lt $RequiredVersion){ Add-PSCPFinding -File $RelativePath -Severity Critical -Area Requires -Line 0 -Column 0 -Message "Requires PowerShell $RequiredVersion; current $($PSVersionTable.PSVersion)" }
$RequiredModules=@();foreach($RequiredModule in @(Get-PSCPProp -Object $Requirements -Name RequiredModules)){ if($null -ne $RequiredModule){ $ModuleName = if($RequiredModule -is [string]){$RequiredModule}elseif($RequiredModule.PSObject.Properties['Name']){$RequiredModule.Name}else{[string]$RequiredModule}; if($ModuleName){$RequiredModules+=@($ModuleName)}; if($ModuleName -and -not (Get-Module -ListAvailable -Name $ModuleName)){ Add-PSCPFinding -File $RelativePath -Severity Error -Area Requires -Line 0 -Column 0 -Message "Declared required module not found here: $ModuleName" } } }
$null=$Inventory.Add([pscustomobject]@{File=$RelativePath;RequiresPS=if($RequiredVersion){[string]$RequiredVersion}else{''};RequiredModules=($RequiredModules -join ',');Commands=(@($Commands|ForEach-Object -Process {$_.C}|Sort-Object -Unique)-join ',');Functions=($Functions -join ',');Parameters=(@($Parameters|ForEach-Object -Process {$_.Extent.Text}|Sort-Object -Unique)-join ';');Variables=($Variables -join ',')})
foreach($CommandName in @($Commands | ForEach-Object -Process {$_.C} | Sort-Object -Unique)){ if($Functions -notcontains $CommandName){ if(-not $CommandCache.ContainsKey($CommandName)){ try{ $CommandCache[$CommandName] = Get-Command -Name $CommandName -ErrorAction Stop | Select-Object -First 1 } catch { $CommandCache[$CommandName] = $null } }; $Resolved = $CommandCache[$CommandName]; if(-not $Resolved){ Add-PSCPFinding -File $RelativePath -Severity Review -Area Dependency -Line 0 -Column 0 -Message "Unresolved command in this checker session: $CommandName" } elseif($Resolved.CommandType -eq 'Alias'){ $ResolvedName = Get-PSCPProp -Object $Resolved -Name ResolvedCommandName; if(-not $ResolvedName){ $ResolvedName = '<unresolvable>' }; Add-PSCPFinding -File $RelativePath -Severity Warning -Area Alias -Line 0 -Column 0 -Message "Alias used: $CommandName -> $ResolvedName" } } }
foreach($Sink in @($Commands | Where-Object -FilterScript {$_.C -in 'Invoke-Expression','iex'})){ Add-PSCPFinding -File $RelativePath -Severity Critical -Area Security -Line $Sink.L -Column $Sink.K -Message 'Invoke-Expression/iex code execution sink' -Text $Sink.T }
foreach($Assignment in @($Ast.FindAll({param($Node) $Node -is [System.Management.Automation.Language.AssignmentStatementAst] -and $Node.Left -is [System.Management.Automation.Language.VariableExpressionAst] -and $Node.Left.VariablePath.UserPath -match '(?i)(password|passwd|pwd|secret|token|apikey|api_key|clientsecret|client_secret|accesstoken|access_token|bearertoken|bearer_token|pat|credential|secretkey|secret_key)' -and $Node.Right.Extent.Text -match '[''\"][^''\"]+[''\"]'},$true))){ Add-PSCPFinding -File $RelativePath -Severity Critical -Area Security -Line $Assignment.Extent.StartLineNumber -Column $Assignment.Extent.StartColumnNumber -Message 'Possible hardcoded secret or credential-like assignment' -Text $Assignment.Extent.Text }
foreach($SecureStringCall in @($Commands | Where-Object -FilterScript {$_.C -eq 'ConvertTo-SecureString' -and $_.T -match '(?i)-AsPlainText' -and $_.T -match '(?i)-Force' -and $_.T -match '[''\"][^''\"]+[''\"]'})){ Add-PSCPFinding -File $RelativePath -Severity Critical -Area Security -Line $SecureStringCall.L -Column $SecureStringCall.K -Message 'Hardcoded plain-text secure string' -Text $SecureStringCall.T }
$Internal = 'New-Object','New-TimeSpan','New-Guid','Set-StrictMode','Set-Location','Set-Variable','Set-PSDebug','Add-Member','Add-Type','Start-Transcript','Stop-Transcript'
$RiskCommands = @($Commands | Where-Object -FilterScript { ($_.C -match '^(Remove|Set|New|Clear|Disable|Enable|Update|Start|Stop|Restart|Add|Grant|Revoke|Disconnect|Connect|Register|Unregister)-' -or $_.C -in 'cmd','cmd.exe','powershell','powershell.exe','pwsh','pwsh.exe','Start-Process') -and $_.C -notin $Internal -and $_.C -notin 'Invoke-Expression','iex' -and $Functions -notcontains $_.C })
foreach($RiskCommand in $RiskCommands){ Add-PSCPFinding -File $RelativePath -Severity Review -Area Risk -Line $RiskCommand.L -Column $RiskCommand.K -Message "High-impact or external-execution command: $($RiskCommand.C)" -Text $RiskCommand.T }
$CommandNames = @($Commands | ForEach-Object -Process {$_.C}); if((Get-PSCPCount -Value @($CommandNames | Where-Object -FilterScript {$_ -match '^(Connect|Get|New|Set|Remove|Update|Invoke|Grant|Revoke)-(Mg|Az|EXO|PnP|Team|Intune|Graph)|^(Connect|Disconnect)-ExchangeOnline|^Connect-MgGraph|^Connect-AzAccount|^Connect-PnPOnline'})) -gt 0){ $null = $Notes.Add("Tool profile in ${RelativePath}: M365/Azure/Graph/Exchange/PnP/Teams-style commands detected; verify module versions, auth context, scopes/roles, tenant target, and WhatIf/ShouldProcess on changes.") }
$StateChanging = @($RiskCommands | Where-Object -FilterScript {$_.C -match '^(Remove|Set|New|Clear|Disable|Enable|Update|Stop|Restart|Add|Grant|Revoke|Register|Unregister)-'}); $SupportsShouldProcess = $false; foreach($Attribute in @($Attributes | Where-Object -FilterScript {$_.TypeName.Name -eq 'CmdletBinding'})){ if((Get-PSCPCount -Value @($Attribute.NamedArguments | Where-Object -FilterScript {$_.ArgumentName -eq 'SupportsShouldProcess' -and (-not $_.Argument -or $_.Argument.Extent.Text -in '$true','1')})) -gt 0){ $SupportsShouldProcess = $true } }; $UsesShouldProcess = $CodeText -match '\$PSCmdlet\.ShouldProcess\s*\(|\.ShouldProcess\s*\('
if((Get-PSCPCount -Value $StateChanging) -gt 0 -and (-not $SupportsShouldProcess -or -not $UsesShouldProcess)){ Add-PSCPFinding -File $RelativePath -Severity Warning -Area Safety -Line 0 -Column 0 -Message 'State-changing commands detected without clear SupportsShouldProcess + ShouldProcess coverage. Review manually; this is not control-flow proof.' }
$StrictModeCommands = @($Commands | Where-Object -FilterScript {$_.C -eq 'Set-StrictMode'}); if((Get-PSCPCount -Value $StrictModeCommands) -eq 0){ Add-PSCPFinding -File $RelativePath -Severity Warning -Area ProdReady -Line 0 -Column 0 -Message 'Set-StrictMode not clearly detected' } elseif((Get-PSCPCount -Value @($StrictModeCommands | Where-Object -FilterScript {$_.T -match '(?i)-Version\s+(Latest|3(?:\.0)?)'})) -eq 0){ Add-PSCPFinding -File $RelativePath -Severity Review -Area ProdReady -Line 0 -Column 0 -Message 'Set-StrictMode found, but -Version Latest/3.0 not clearly detected' }
if(-not (Test-PSCPEap -Ast $Ast)){ Add-PSCPFinding -File $RelativePath -Severity Warning -Area ProdReady -Line 0 -Column 0 -Message "`$ErrorActionPreference='Stop' not clearly detected" }
$WriteHostCount = Get-PSCPCount -Value @($Commands | Where-Object -FilterScript {$_.C -eq 'Write-Host'}); if($WriteHostCount){ Add-PSCPFinding -File $RelativePath -Severity Review -Area Pipeline -Line 0 -Column 0 -Message "Write-Host used $WriteHostCount time(s); review structured output / Write-Verbose / Write-Information." }
$GlobalCount = Get-PSCPCount -Value @($Variables | Where-Object -FilterScript {$_ -match '^global:'}); if($GlobalCount){ Add-PSCPFinding -File $RelativePath -Severity Warning -Area Scope -Line 0 -Column 0 -Message "Global variables used: $GlobalCount" }
$ValidationCount = Get-PSCPCount -Value @($Attributes | Where-Object -FilterScript {$_.TypeName.Name -match '^Validate'}); if((Get-PSCPCount -Value $Parameters) -gt 0 -and -not $ValidationCount){ Add-PSCPFinding -File $RelativePath -Severity Review -Area Validation -Line 0 -Column 0 -Message 'Parameters found but no Validate* attributes detected' }
$WmiCount = Get-PSCPCount -Value @($Commands | Where-Object -FilterScript {$_.C -eq 'Get-WmiObject'}); if($WmiCount){ Add-PSCPFinding -File $RelativePath -Severity Warning -Area Deprecated -Line 0 -Column 0 -Message "Get-WmiObject used $WmiCount time(s); prefer Get-CimInstance where practical" }
$SleepCount = Get-PSCPCount -Value @($Commands | Where-Object -FilterScript {$_.C -eq 'Start-Sleep'}); if($SleepCount){ Add-PSCPFinding -File $RelativePath -Severity Review -Area Timing -Line 0 -Column 0 -Message "Start-Sleep used $SleepCount time(s); prefer polling when waiting for state" }
foreach($Token in @($Tokens | Where-Object -FilterScript {$_.Kind -eq 'Comment'})){ if($Token.Text -match '(?i)\b(TODO|FIXME|HACK|TEMP)\b'){ Add-PSCPFinding -File $RelativePath -Severity Review -Area Marker -Line $Token.Extent.StartLineNumber -Column $Token.Extent.StartColumnNumber -Message 'Unresolved marker in comment' -Text $Token.Text } }
$Rules = @(
@('Warning','Security',('(?:powershell(?:\.exe)?|pwsh(?:\.exe)?)\b[^\r\n]{0,160}-(?:ExecutionPolicy|ep)\s+Bypass|Set-ExecutionPolicy\s+Bypass'),'ExecutionPolicy bypass pattern'),
@('Warning','Security',('-(?:EncodedCommand|enc)\b|FromBase64String\s*\(|\[scriptblock\]::Create\s*\('),'Encoded/base64/scriptblock creation pattern'),
@('Review','Security',('\[char\]\s*\d|\[char\[\]\]|\-join\s*\[char\]'),'Possible obfuscation pattern'),
@('Warning','Errors','SilentlyContinue','Silent error handling; review whether failures are hidden'),
@('Warning','Errors','catch\s*\{\s*\}','Empty catch block'),
@('Warning','Suppression','\*>?\s*\$null|2>\s*\$null|\|\s*Out-Null\b','Output/error suppression'),
@('Review','Network',('http'+'s?://'),'Hardcoded URL'),
@('Review','Paths',('[A-Z]:\\|\\\\[a-zA-Z0-9._$-]+|/(Users|home|var|etc|tmp|opt|usr|root)/'),'Hardcoded absolute/UNC/Unix-style path')
)
foreach($Rule in $Rules){ foreach($Match in [regex]::Matches($CodeText,$Rule[2],'IgnoreCase,Multiline')){ $Location = Get-PSCPLocation -Text $CodeText -Index $Match.Index; Add-PSCPFinding -File $RelativePath -Severity $Rule[0] -Area $Rule[1] -Line $Location.Line -Column $Location.Column -Message $Rule[3] -Text $Match.Value } }
if($PssaAvailable){ try{ Invoke-ScriptAnalyzer -Path $File.FullName -Severity Error,Warning,Information -ErrorAction Stop | ForEach-Object -Process { $Severity = Get-PSCPProp -Object $_ -Name Severity; $MappedSeverity = if($Severity -eq 'Error'){'Error'}elseif($Severity -eq 'Warning'){'Warning'}else{'Review'}; $Extent = Get-PSCPProp -Object $_ -Name Extent; $Text = if($Extent){$Extent.Text}else{''}; $PssaDiag++; Add-PSCPFinding -File $RelativePath -Severity $MappedSeverity -Area PSSA -Line (Get-PSCPProp -Object $_ -Name Line) -Column (Get-PSCPProp -Object $_ -Name Column) -Message "$((Get-PSCPProp -Object $_ -Name RuleName)): $((Get-PSCPProp -Object $_ -Name Message))" -Text ([string]$Text) } } catch { Add-PSCPFinding -File $RelativePath -Severity Review -Area PSSA -Line 0 -Column 0 -Message $_.Exception.Message } }
Add-PSCPSummary -File $RelativePath -Start $StartFinding -Raw $Raw -Commands $Commands -Functions $Functions -Parameters $Parameters -Variables $Variables
} catch {
Add-PSCPFinding -File $RelativePath -Severity Critical -Area Analyzer -Line (Get-PSCPProp -Object $_.InvocationInfo -Name ScriptLineNumber) -Column 0 -Message "Analyzer failed on this file: $($_.Exception.Message)"
Add-PSCPSummary -File $RelativePath -Start $StartFinding -Raw $Raw -Commands $Commands -Functions $Functions -Parameters $Parameters -Variables $Variables
}
}
$Recommendations = [Collections.Generic.List[string]]::new()
if((Get-PSCPCount -Value @($Findings | Where-Object -FilterScript {$_.Severity -eq 'Critical'})) -gt 0){ $null = $Recommendations.Add('BLOCK: Critical findings exist. Do not run affected scripts until fixed/reviewed.') }
if((Get-PSCPCount -Value @($Findings | Where-Object -FilterScript {$_.Area -eq 'Parser'})) -gt 0){ $null = $Recommendations.Add('Fix parser/syntax errors first; other findings may be unreliable until syntax is valid.') }
if((Get-PSCPCount -Value @($Findings | Where-Object -FilterScript {$_.Area -eq 'Security'})) -gt 0){ $null = $Recommendations.Add('Review Security findings for secrets, code execution, bypasses, obfuscation, or embedded auth material.') }
if((Get-PSCPCount -Value @($Findings | Where-Object -FilterScript {$_.Area -eq 'Dependency'})) -gt 0){ $null = $Recommendations.Add('Confirm unresolved commands against the real target machine/session, module versions, and M365/Azure service connection context.') }
if((Get-PSCPCount -Value @($Findings | Where-Object -FilterScript {$_.Area -eq 'Safety'})) -gt 0){ $null = $Recommendations.Add('For state-changing automation, verify each destructive/change path has WhatIf/ShouldProcess or an equivalent explicit safety gate.') }
if((Get-PSCPCount -Value @($Findings | Where-Object -FilterScript {$_.Area -in 'ProdReady','Errors','Suppression'})) -gt 0){ $null = $Recommendations.Add('Tighten production guardrails: StrictMode, terminating errors, non-empty catch blocks, and no hidden output/error paths unless justified.') }
if((Get-PSCPCount -Value $Recommendations) -eq 0){ $null = $Recommendations.Add('No blocking recommendation generated from detected findings. This is still static analysis only, not runtime proof.') }
$null=$Notes.Add("Files scanned: $((Get-PSCPCount -Value $Summary)); inventory rows: $((Get-PSCPCount -Value $Inventory)); findings: $((Get-PSCPCount -Value $Findings)); PSSA diagnostics emitted: $PssaDiag; PSSA ran: $PssaAvailable")
'=== TOOL NOTES ==='
$Notes | Sort-Object -Unique | ForEach-Object -Process { "- $_" }
''
'=== SUMMARY ==='
$Summary | Sort-Object -Property Score,File | Format-Table -AutoSize | Out-String -Width 4096
'=== INVENTORY ==='
$Inventory | Sort-Object -Property File | Format-Table -AutoSize | Out-String -Width 4096
if((Get-PSCPCount -Value $Findings) -gt 0){ '=== DETAILED FINDINGS ==='; $Findings | Sort-Object -Property File,@{Expression={switch($_.Severity){Critical{0}Error{1}Warning{2}Review{3}default{4}}}},Line,Column | Format-Table -AutoSize -Property File,Severity,Area,Line,Column,Message,Text | Out-String -Width 4096 } else { 'No static findings detected. This does not prove runtime safety.' }
'=== RECOMMENDATIONS ==='
$Recommendations | ForEach-Object -Process { "- $_" }
'Static analysis complete. Target scripts were NOT executed. Findings, summary, inventory, PSSA diagnostics, and tool notes were emitted; no detected findings were intentionally suppressed.'
}
